main: net.simplyvanilla.simplyvotifier.SimplyVotifier
name: SimplyVotifier
description: A plugin that gets notified when votes are made for the server on toplists.
version: @version@
api-version: 1.19

author: Simply Vanilla
website: https://github.com/SimplyVanilla/SimplyChat
folia-supported: true
